## name EmptyReturn
## failures 1
## cut

return;

## name BareReturn
## failures 1
## cut

sub foo { return }

## name ReturnEmptyList
## failures 0
## cut

return ();

## name ReturnScalar
## failures 0
## cut

return undef;

## name ReturnList
## failures 0
## cut

return 1, 2, 3;

## name ReturnModified
## failures 1
## cut

return if foo();

## name ReturnMidStatement
## failures 1
## cut

foo() or return;
